RulesToSuppress:
  - id: W58
    reason: Lambda function already have permission to write CloudWatch Logs
  - id: 'W92'
    reason: 'Do not need to set reservedConcurrentExecutions for lambda'
  - id: 'W5'
    reason: 'This solution will access external traffic for upgrading'
  - id: 'W35'
    reason: 'the check is not necessary because target is used to store accessing log'