version: 0.2

env:
  shell: bash
  exported-variables:
    - BSS_IMAGE_ASSET_REPOSITORY_NAME
    - BUILD_VERSION
    - CN_ASSETS
    - GLOBAL_ASSETS
    - ECR_REPOS
    - CN_ECR_REPOS
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - git clone https://github.com/awslabs/quantum-ready-solution-for-drug-discovery.git -b main /tmp/repo
      - rsync -av /tmp/repo/source ${CODEBUILD_SRC_DIR}/
      - rsync -av /tmp/repo/docs ${CODEBUILD_SRC_DIR}/
      - pwd
      - ls -al
      - cp ./.cfn-nag-ignore-lists.yml ./.cfnnag_global_suppress_list
      # - sed -i '9,$d' ${CODEBUILD_SRC_DIR}/source/docs/mkdocs.zh.yml
      # - echo '  - deployment-guide.md' >>${CODEBUILD_SRC_DIR}/source/docs/mkdocs.zh.yml
      # - cp -rf ${CODEBUILD_SRC_DIR}/source/docs ${CODEBUILD_SRC_DIR}/
      - export BSS_IMAGE_ASSET_REPOSITORY_NAME=$(echo "$SOLUTION_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
      - export BUILD_VERSION=$(git -c pager.tag=false tag --points-at $(git rev-parse --short HEAD) | tail -1 || echo latest)
      - if [ -z $BUILD_VERSION ]; then BUILD_VERSION='latest'; fi
      - export CN_ASSETS='cn/'
      - echo "build version $BUILD_VERSION"
      - export GLOBAL_ASSETS='custom-domain/,default/'
  build:
    commands:
      - ${CODEBUILD_SRC_DIR}/deployment/build-s3-dist.sh ${DIST_OUTPUT_BUCKET} ${SOLUTION_NAME} ${BUILD_VERSION}
      - mkdir -p deployment/open-source/ && touch deployment/open-source/.empty
  post_build:
    commands:
      - aws s3 cp s3://solutions-build-assets/changelog-spec.yml buildspec.yml || true
      - |-
        set -euxo pipefail
        __dir="${CODEBUILD_SRC_DIR}/deployment"
        function join_by { local IFS="$1"; shift; echo "$*"; }
        export ECR_REPOS=$(join_by , `cat "${__dir}/ecr-repos"`)
        export CN_ECR_REPOS=$(join_by , `cat "${__dir}/cn-ecr-repos"`)
artifacts:
  files:
    - .git/**/*
    - deployment/**/*
    - docs/**/*
    - buildspec.yml
    - CHANGELOG.md
    - .cfnnag_*

