AWSTemplateFormatVersion: '2010-09-09'
Description: Cross region event bus for braket

Parameters:
  TargetRegion:
    Type: String
    Description: Target Region
    Default: us-east-1

Resources:
  EventRuleRegion1:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: Routes to targetRegion event bus
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - aws.braket
        detail:
          - Braket Task State Change
      Targets:
        - Arn: !Sub arn:aws:events:${TargetRegion}:${AWS::AccountId}:event-bus/default
          Id: 'CrossRegionDestinationBus'
          RoleArn: !GetAtt 
            - EventBridgeIAMrole
            - Arn
  EventBridgeIAMrole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub events.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: PutEventsDestinationBus
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'events:PutEvents'
                Resource:
                  - !Sub arn:aws:events:${TargetRegion}:${AWS::AccountId}:event-bus/default
