FROM 292282985366.dkr.ecr.us-west-2.amazonaws.com/amazon-braket-base-jobs:1.0-cpu-py37-ubuntu18.04

RUN python3 -m pip install --upgrade pip

RUN python3 -m pip install dimod==0.10.12 \
                           dwave-system==1.15.0 \
                           dwave-neal==0.5.9 \
                           networkx==2.6.3 \
                           amazon-braket-ocean-plugin==1.0.7 \
                           Cython==0.29.32 \
                           biopandas==0.4.1 \
                           py3Dmol==1.8.0 \
                           ipywidgets==7.7.0