name: Cfn-nag check
'on':
  pull_request: {}
  workflow_dispatch: {}
jobs:
  cfn-nag:
    runs-on: ubuntu-latest
    env:
      CI: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.head.ref }}'
          repository: '${{ github.event.pull_request.head.repo.full_name }}'
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: |
          cd source/
          npm install
      - name: synth
        run: |
          cd source/
          npx cdk synth --json --output cdk.out -q
      - uses: stelligent/cfn_nag@master
        with:
          input_path: source/cdk.out/
          extra_args: >-
            --template-pattern ..*.template.json --fail-on-warnings -b .cfn-nag-ignore-lists.yml --print-suppression
