name: Run eslint
'on':
  pull_request: {}
  workflow_dispatch: {}
jobs:
  eslint:
    runs-on: ubuntu-latest
    env:
      CI: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: '${{ github.event.pull_request.head.ref }}'
          repository: '${{ github.event.pull_request.head.repo.full_name }}'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          cd source/
          npm install
      - name: Run eslint
        run: |
          cd source/
          npm run eslint

