name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python3 -m pip install lxml_html_clean
          python3 -m pip install mkdocs==1.2.3            # install mkdocs 
          python3 -m pip install mkdocs-material==8.1.8   # install material theme
          python3 -m pip install mkdocs-jupyter==0.20.0    # install plugin for jupyter notebook
          python3 -m pip install ipython_genutils==0.2.0
          python3 -m pip install mkdocs-material-extensions==1.0.3
          python3 -m pip install mkdocs-markdownextradata-plugin==0.2.5
          python3 -m pip install Jinja2==3.0.3
      
      - name: Build mkdocs
        run: |
          mkdocs build -f ./docs/mkdocs.en.yml -s
          mkdocs build -f ./docs/mkdocs.zh.yml -s
          cp -av ./docs/index.html ./docs/site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site

